/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content px-20 pt-20 mb-20 w-full flex items-center justify-center">
        <div className="max-w-[900px]">
          <div className="flex">
            <img src="/images/logo.png" alt="logo" width={69} />
            <div className="flex flex-col w-full justify-center items-center">
              <h1 className="text-xl font-bold">
                Philippine Women&apos;s University
              </h1>
              <h2 className="text-lg font-semibold">Ethics Review Board</h2>
            </div>
          </div>
          <div className="border-2 border-black p-3 mt-20">
            <h1 className="text-base font-bold">
              Guidelines in filling up this form:
            </h1>
            <ol className="ml-10">
              <li>
                <div className="flex">
                  <span>1.</span>
                  <p className="ml-5">
                    This file is composed of five(5) forms compiled in one word
                    file. The following forms composed all the documents needed
                    for Research Ethics Review:
                  </p>
                </div>
                <ul className="list-decimal ml-20 font-semibold">
                  <li className="flex">
                    <span>a.</span>
                    <p className="ml-5">Review Checklist</p>
                  </li>
                  <li className="flex">
                    <span>b.</span>
                    <p className="ml-5">Registration and Application Form</p>
                  </li>
                  <li className="flex">
                    <span>c.</span>
                    <p className="ml-5">Initial Review and Resubmission Form</p>
                  </li>
                  <li className="flex">
                    <span>d.</span>
                    <p className="ml-5">Protocol Assessment Form</p>
                  </li>
                  <li className="flex">
                    <span>e.</span>
                    <p className="ml-5">Informed Consent Assessment Form</p>
                  </li>
                </ul>
              </li>
              <li>
                <div className="flex">
                  <span>2.</span>
                  <p className="ml-5">
                    Please complete all necessary blanks/items, otherwise put
                    N/A.
                  </p>
                </div>
              </li>
              <li>
                <div className="flex">
                  <span>3.</span>
                  <p className="ml-5">
                    In the Protocol Assessment Form and Informed Consent
                    Assessment Form,please make sure that the correct page
                    numbers and paragraphs that correspond to your manuscript
                    are indicated in the{" "}
                    <span className="italic font-medium">
                      “Page and paragraph where it can be found”
                    </span>
                    columns. Make sure that the page numbers in the form are
                    correct when checked against the manuscript
                  </p>
                </div>
              </li>
              <li>
                <div className="flex">
                  <span>4.</span>
                  <p className="ml-5">
                    Put a highlight on the corresponding page and paragraph
                    located in the manuscript.
                  </p>
                </div>
              </li>
              <li>
                <div className="flex">
                  <span>5.</span>
                  <p className="ml-5">
                    Make sure that your signature is inserted in the form.
                  </p>
                </div>
              </li>
            </ol>
          </div>
          <h1 className="uppercase text-lg font-bold w-full text-center py-10">
            Review Checklist
          </h1>
          <h1 className="uppercase text-md font-bold w-full pb-10">
            STUDY PROTOCOL INFORMATION
          </h1>
          <table className="border-2 border-black w-full">
            <tbody>
              <tr className="border-2 border-black">
                <td className="text-center pb-5">PWUERB Code:1</td>
                <td className="border-2 border-black w-[500px]"></td>
              </tr>
              <tr className="border-2 border-black">
                <td className="pl-3 pb-10 pt-5">Study Protocol Title:</td>
                <td className="border-2 border-black"></td>
              </tr>
              <tr className="border-2 border-black">
                <td className="pl-3 pb-5">Principal Investigator:</td>
                <td className="border-2 border-black"></td>
              </tr>
              <tr className="border-2 border-black">
                <td className="pl-3 pb-5">Study Protocol Submission Date:</td>
                <td className="border-2 border-black"></td>
              </tr>
              <tr className="border-2 border-black">
                <td className="pl-3 pb-5">Verified Complete by:</td>
                <td className="border-2 border-black pl-3 pb-5">
                  ERB SECRETARIAT
                </td>
              </tr>
            </tbody>
          </table>
          <div className="px-20 pt-10">
            <div className="flex font-medium">
              <span>A.</span>
              <span className="ml-3">Basic Documents (must submit)</span>
            </div>
            <div className="flex font-medium">
              <input type="checkbox" />
              <span className="ml-3">Review Checklist</span>
            </div>
            <div className="flex font-medium">
              <input type="checkbox" />
              <span className="ml-3">Registration and Application Form</span>
            </div>
            <div className="flex font-medium">
              <input type="checkbox" />
              <span className="ml-3">Protocol Assessment Form</span>
            </div>
            <div className="flex font-medium">
              <input type="checkbox" />
              <span className="ml-3">Study Protocol</span>
            </div>
            <div className="flex font-medium">
              <input type="checkbox" />
              <span className="ml-3">
                Data collection forms (including CRFs)
              </span>
            </div>
          </div>
          <div className="w-full flex flex-col justify-center items-center gap-3 text-sm mt-10">
            <p>
              Office of Research and Development, Mezzanine Floor, J. Nakpil
              Wing,
            </p>
            <p>Philippine Women’s University, 1743 Taft Avenue, Manila</p>
            <p>
              Email:{" "}
              <a href="mailto:ethics@pwu.edu.ph" className="text-[#0000EE]">
                ethics@pwu.edu.ph
              </a>
            </p>
            <p>Tel: 8526 8421 loc 139</p>
          </div>
        </div>
      </main>
    </>
  );
}
